### ISSUE TITLE
Compile error with base-4.5

### ISSUE THREAD

**Issue by hvr** [libscott/quickson#1]
Fyi, the following happens w/ GHC 7.4

You can either set a tigher bound `base >= 4.6` or try to depend on `ghc-prim >= 0.2` and see whether `aeson-quick` still works if you want to support (the rather old) GHC 7.4.

```
Configuring component lib from aeson-quick-0.1.1.1...
Preprocessing library aeson-quick-0.1.1.1...

Data/Aeson/Quick.hs:32:8:
    Could not find module `GHC.Generics'
    It is a member of the hidden package `ghc-prim'.
    Perhaps you need to add `ghc-prim' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

**Comment by ssadler** [comment]
Great, now [support 7.4!](https://github.com/libscott/aeson-quick/commit/bc6a54aac2f5a855c8246e557327e9d8276894ad). Thanks
